CREATE TABLE `GP_PAY_FEE_INFO` (
  `ID` varchar(100) NOT NULL,
  `BUSINESS_NO` varchar(100) NOT NULL,
  `AMOUNT` double NOT NULL,
  `STATUS` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

